apiVersion: storage.loft.sh/v1
kind: NodeProvider
metadata:
  name: metal3
spec:
  displayName: "Metal3 Bare Metal Hosts"
  metal3:
    clusterRef:
      cluster: loft-cluster
      namespace: default
    deploy:
      multus:
        enabled: true
      metal3:
        enabled: true
      dhcp:
        enabled: true
        helmValues: |
          networkAttachmentDefinition:
            vip: 192.168.100.4/24
    nodeTypes:
      - name: vm
